import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Guest from '@/components/Guest'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Guest guestName="Luke Gygax"/>
        <Guest guestName="Alphinius Goo" alternateName="Kim" />
        <Guest guestName="Gooeycube"/>        
        <Guest guestName="Boof" alternateName="Jessica Sizemore" />
        <Guest guestName="Bruce Cordell"/>
        <Guest guestName="Darrell Hayhurst"/>
        <Guest guestName="Cosmo Joe" alternateName="RPEX" />        
        <Guest guestName="Karl Keesler"/>
        <Guest guestName="Sara Martinez"/>
        <Guest guestName="Tommy Rice" alternateName="Tommy" />
        <Guest guestName="Jeff Richard"/>
        <Guest guestName="Tracy Sizemore"/>
        <Guest guestName="Tonya Woldridge"/>        
      </main>
    </>
  )
}
